src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: MovieRepository::class)]
class Movie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 3,
        max: 50,)]
    private ?string $title = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    private ?int $release_year = null;

    #[ORM\Column(length: 2555, nullable: true)]
    #[Assert\NotBlank]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_path = null;

    #[ORM\ManyToMany(targetEntity: Actor::class, mappedBy: 'movies')]
    private Collection $actors;

    #[ORM\OneToMany(targetEntity: Comments::class, mappedBy: 'movie')]
    private Collection $comments;

    #[ORM\OneToMany(targetEntity: Rating::class, mappedBy: 'movie')]
    private Collection $rating;

    #[ORM\Column(nullable: true)]
    private ?float $average_rating = null;

    #[ORM\ManyToMany(targetEntity: Categories::class, inversedBy: 'movies')]
    private Collection $categories;

    public function __construct()
    {
        $this->actors = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->rating = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getReleaseYear(): ?int
    {
        return $this->release_year;
    }

    public function setReleaseYear(?int $release_year): static
    {
        $this->release_year = $release_year;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->image_path;
    }

    public function setImagePath(?string $image_path): static
    {
        $this->image_path = $image_path;

        return $this;
    }

    /**
     * @return Collection<int, Actor>
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }

    public function addActor(Actor $actor): static
    {
        if (!$this->actors->contains($actor)) {
            $this->actors->add($actor);
            $actor->addMovie($this);
        }

        return $this;
    }

    public function removeActor(Actor $actor): static
    {
        if ($this->actors->removeElement($actor)) {
            $actor->removeMovie($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setMovie($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getMovie() === $this) {
                $comment->setMovie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Rating>
     */
    public function getRating(): Collection
    {
        return $this->rating;
    }

    public function addRating(Rating $rating): static
    {
        if (!$this->rating->contains($rating)) {
            $this->rating->add($rating);
            $rating->setMovie($this);
        }

        return $this;
    }

    public function removeRating(Rating $rating): static
    {
        if ($this->rating->removeElement($rating)) {
            // set the owning side to null (unless already changed)
            if ($rating->getMovie() === $this) {
                $rating->setMovie(null);
            }
        }

        return $this;
    }

    public function getAverageRating(): ?float
    {
        return $this->average_rating;
    }

    public function setAverageRating(?float $average_rating): static
    {
        $this->average_rating = $average_rating;

        return $this;
    }

    /**
     * @return Collection<int, Categories>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Categories $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
        }

        return $this;
    }

    public function removeCategory(Categories $category): static
    {
        $this->categories->removeElement($category);

        return $this;
    }
}

src/Controller/MoviesController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Movie;
use App\Entity\Rating;
use App\Entity\Comments;
use App\Entity\Categories;
use App\Form\CommentFormType;
use App\Service\MoviesService;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MoviesController extends AbstractController
{
    private $em;
    private $moviesService;
    private $ur;
    public function __construct(EntityManagerInterface $em, MoviesService $moviesService, UserRepository $ur) 
    {
        $this->em = $em;
        $this->moviesService = $moviesService;
        $this->ur = $ur;
    }

    #[Route('/', name: '')]
    public function home(Request $request, PaginatorInterface $paginator)
    {
        return $this->index($request, $paginator);
    }

    #[Route('/movies', name: 'movies')]
    public function index(Request $request, PaginatorInterface $paginator): Response
    {
        $movies = $this->em->getRepository(Movie::class)->findAll();

        $pagination = $paginator->paginate(
            $movies,
            $request->query->getInt('page', 1),
            3
        );

        return $this->render('movies/index.html.twig', [
            'movies' => $movies,
            'pagination' => $pagination,

        ]);
    }

    #[Route('/movies/search', name: 'movies_search')]
    public function search(): Response
    {
        return $this->render('movies/search.html.twig', [
            'movies' => $this->em->getRepository(Movie::class)->findAll(),
            'categoriesSelect' => $this->em->getRepository(Categories::class)->findAll()
        ]);
    }

    #[Route('/movies/{id}', methods: ['GET','POST'], name: 'show_movie')]
    public function show(int $id, Request $request): Response
    {   
        $movie = $this->em->getRepository(Movie::class)->find($id);
        $existingRating = $this->moviesService->getExistingRating($movie, $this->getUser());
        $comment = new Comments();
        $user = $this->getUser();
        if ($user) {
            $userInfo = $this->ur->find($user);
            $comment->setAuthor($userInfo->getEmail());
            $comment->setCreatedAt(new DateTime());
        }
        $commentForm = $this->createForm(CommentFormType::class, $comment);
        $commentForm->handleRequest($request);

        if($this->moviesService->show($id, $movie, $comment, $commentForm, $this->getUser()))
            $this->addFlash('success','Comment added successfully');

        return $this->render('movies/show.html.twig', [
            'movie' => $movie,
            'commentForm' => $commentForm->createView(),
            'existingRating' => $existingRating
        ]);
    }

    #[Route('/movie/rateMovie/{id}', methods: ['GET','POST'], name: 'rate_movie')]
    public function rateMovie(Request $request, int $id): Response
    {
        $ratingValue = $request->get('rating');
        $movie = $this->em->getRepository(Movie::class)->find($id);

        return $this->moviesService->rateMovie($movie, $ratingValue, $this->getUser());
    }

}

templates/movies/edit.html.twig
{% extends "./base.html.twig" %}

{% block title %}Edit Movie {% endblock %}

{% block body %}
<div class="w-4/5 m-auto pt-40">
    <h1 class="text-6xl text-center pb-12">
        Edit Movie
    </h1>

    {{ form_start(form) }}

        {{ form_widget(form) }}
        
        <button    
            type="submit"
            class="btn btn-outline-dark uppercasetext-lg py-4 px-12 rounded mt-2">
            Submit Post
        </button>

    {{ form_end(form) }}
</div>
{% endblock %}

templates/movies/index.html.twig
{% extends "./base.html.twig" %}

{% block title %} Movies {% endblock %}

{% block body %}
    <div class="w-4/5 m-auto text-center" >
        <div class=" border-b border-gray-200">
            <h1 class="text-6xl pt-12 pb-8">
                Movies
            </h1>

        </div>
        <div class="d-flex">
            <div class="mx-auto w-4/5 my-8">
                <a 
                    href="/movies/search" 
                    class="uppercase border border-gray-500 text-gray-600 text-lg py-4 px-12 rounded transition transition-all hover:bg-gray-800 hover:text-white">
                    Find movie
                </a>
            </div>
        </div>
    </div>


    
    <div class="md:grid lg:grid-cols-3 gap-20 w-4/5 mx-auto py-15" id="resultsList">
        <!-- Review Item -->
        {% for movie in pagination %}
            <div class="text-center pt-8 pb-4">
                <h2 class="card-title text-gray-700 font-bold text-3xl py-2" style="min-height: 80px;">
                    {{ movie.title }}
                </h2>
                
                <div style="text-align: -webkit-center;">
                    <img
                        src="{{ movie.imagePath }}"
                        alt=""
                        class="shadow-xl rounded-md img-fluid max-width-100 max-height-100"
                        style="max-width: 400px; max-height: 400px;"
                    />
                </div>


            <p class="card-description text-base text-gray-700 pt-4 pb-10 leading-8 font-light overflow-hidden h-60 mb-10 min-vh-30">
                {{ movie.description }}
            </p>

            <a href="/movies/{{ movie.id }}" class="btn btn-outline-dark uppercasetext-lg py-4 px-12 rounded">
                Keep Reading
            </a>
            </div>
        {% endfor %}

    </div>
    <div class="w-4/5 mt-4 m-auto text-center pagination" >
        {{ knp_pagination_render(pagination,
         '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig',) }}
    </div>

{% endblock %}

templates/movies/search.html.twig
{% extends "./base.html.twig" %}

{% block title %} Movies search {% endblock %}

{% block body %}
<div class="w-4/5 m-auto text-center" >
    <div class=" border-b border-gray-200">
        <h1 class="text-6xl pt-12 pb-8">
            Movies search
        </h1>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form class="d-flex">
                <input class="form-control me-2 py-4 px-6 border-gray-500 w-50" type="search" placeholder="Search" aria-label="Search" id="searchInput">
                <div class="m-2">
                        Categories:
                </div>
                <select class="form-select me-2 py-4 px-6 border-gray-500" multiple id="categorySelect">
                     {% for category in categoriesSelect %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </form>
        </div>
    </div>
</div>



    
<div class="md:grid lg:grid-cols-3 gap-20 w-4/5 mx-auto py-15 minh-80" id="resultsList">
    <!-- Review Item -->
    {% for movie in movies %}
        <div class="cards text-center pt-8 pb-4" data-categories="{% for category in movie.categories %}{{ category.name|lower }}{% if not loop.last %},{% endif %}{% endfor %}">
            <h2 class="card-title text-gray-700 font-bold text-3xl py-2" style="min-height: 80px;">
                {{ movie.title }}
            </h2>

            <div class="mb-1" style="min-height: 80px;">
            {% for category in movie.categories %}
                <span class="badge bg-primary mt-1">{{ category.name }}</span>
            {% endfor %}
            </div>
            
            <div style="text-align: -webkit-center;">
                <img
                    src="{{ movie.imagePath }}"
                    alt=""
                    class="shadow-xl rounded-md img-fluid max-width-100 max-height-100"
                    style="max-width: 400px; max-height: 400px;"
                />
            </div>

            <p class="card-description text-base text-gray-700 pt-4 pb-10 leading-8 font-light overflow-hidden h-60 mb-10 min-vh-30">
                {{ movie.description }}
            </p>

            <a href="/movies/{{ movie.id }}" class="btn btn-outline-dark uppercasetext-lg py-4 px-12 rounded">
                Keep Reading
            </a>
        </div>
    {% endfor %}
</div>


    {% block javascript %}
        <script src="{{ asset("javascript/searchbar.js") }}"></script>
    {% endblock %}

{% endblock %}

templates/movies/show.html.twig
{% extends "./base.html.twig" %}

{% block title %} {{ movie.title }} {% endblock %}

{% block body %}
    <div class="sm:w-3/5 w-4/5 mx-auto">
        <h1 class="pt-20 sm:text-5xl md:text-7xl text-4xl font-bold text-center">
            {{ movie.title }}
        </h1>

        <div class="py-10 text-center">
            <div class="sm:pt-1">
            
                <p class="text-sm text-gray-600 font-bold average-rating">
                Categories:
                </p><br>

                    <div class="row">
                        {% if movie.categories|length > 0 %}
                            <div class="row">
                                {% for category in movie.categories %}
                                    <div class="col-lg-3 col-md-4 col-sm-6 mb-3">
                                        <div class="card">
                                            <div class="card-body">
                                                <p class="card-link">{{ category.name }}</p>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        {% else %}
                            <p>No categories found.</p>
                        {% endif %}
                    </div>
                    <br>

                <p class="text-sm text-gray-600">
                Release Year: {{movie.releaseYear}} <br>
                </p>

                <p class="text-sm text-gray-600 font-bold average-rating">
                Average rating: 
                {% if movie.averageRating|trim %}
                    {{ movie.averageRating }}
                    {% else %}
                    0
                {% endif %} 
                / 5 <br>
                </p>
            </div>
        </div>

        <img
            src="{{ movie.imagePath }}"
            class="rounded-xl w-full shadow-xl movie-img-size mx-auto d-block"
            alt="Icon"
        />

        <p class="text-xl py-6">
            {{ movie.description }}
        </p>

    </div>

<div class="row">
    <div class="col mt-2">
        <h3><i class="pr-3 fas fa-comment pl-8"></i>{{ movie.comments|length }} Comments</h3>
        <hr>
        {% if app.user %}
            <div class="row mb-5">
                <div class="col mt-6">
                    <div class="rounded">
                        <div class="shadow p-3">
                            <div class="comment-container d-inline-block pl-3 align-top">
                                <img class="comment-img rounded-circle icon-img-size" src="{{ asset('images/usericon.png') }}" alt="User Icon">
                                <span class="commenter-name">{{app.user.email}}</span>
                                {{ form_start(commentForm) }}

                                    <div class="form-floating mt-2">
                                        <input type="hidden" name="comment_form[author]" value="{{ app.user.email }}">
                                        <input type="hidden" name="comment_form[createdAt]" value="{{ 'now'|date('Y-m-d H:i:s') }}">

                                        {{ form_row(commentForm.content) }}
                                    </div>
                                    <button type="submit" class="btn btn-info mt-2">Comment</button>
                                {{ form_end(commentForm) }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col mt-6 text-center">
                    <div class="rounded">
                        <div class="shadow p-3 w-50 mx-auto">
                            <h1><b>Rate This Film</b></h1>
                            <div class="justify-content-center mt-6 film" data-film-id="{{ movie.id }}">
                                <span class="fa fa-star rate-button" data-rating="1"></span>
                                <span class="fa fa-star rate-button" data-rating="2"></span>
                                <span class="fa fa-star rate-button" data-rating="3"></span>
                                <span class="fa fa-star rate-button" data-rating="4"></span>
                                <span class="fa fa-star rate-button" data-rating="5"></span>
                            </div>
                        </div>
                    </div>
                </div>

                <input type="hidden" id="existingRating" value="{{ existingRating ? existingRating.score : '' }}">
            </div>
        {% endif %}


        {% for comment in movie.comments %}
        <div class="row mb-3">
            <div class="col">
                <div class="rounded">
                    <div class="shadow p-3 w-50">
                        <div class="row">
                            <div class="col-auto">
                                <img class="comment-img rounded-circle icon-img-size" src="{{ asset('images/usericon.png') }}" alt="User Icon">
                            </div>
                            <div class="col">
                                <div class="comment-container d-inline-block pl-3 align-top">
                                    <span class="commenter-name">{{ comment.author }}</span>
                                    <small class="text-muted">about {{ comment.createdAt|ago }}</small>
                                    <br>
                                    <span class="comment mt-2">{{ comment.content }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        {% endfor %}
    </div>
</div>

    {% block javascript %}
        <script src="{{ asset("javascript/rateMovie.js") }}"></script>
    {% endblock %}

{% endblock %}